import { fetchMonitor, fetchServerGroup, fetchServerMetrics, fetchService, fetchSetting } from "./api";
import { billingInfo, esc, formatBytes, formatSpeed, formatTime, formatUptime, level, parsePublicNote, serverInfo } from "./format";
import { chart, formatValue } from "./charts";
import { locale, t, toggleLocale, useBackendLocale } from "./i18n";
import { countryPoint, worldBorders, worldLand } from "./world-map";
import { applyThemeSettings, defaultThemeSettings, installCustomCode, readThemeSettings } from "./theme-settings";
import type { CycleTransferData, MetricDataPoint, MetricPeriod, MetricType, NezhaMonitor, NezhaServer, ServerGroup, ServerMetricsData, ServiceData } from "./types";

const root = document.querySelector<HTMLDivElement>("#app")!;
const state = {
  siteName: "Nezha Pocket Console", version: "", connected: false, attempts: 0, now: 0, servers: [] as NezhaServer[], groups: [] as ServerGroup[],
  group: sessionStorage.getItem("nezha-pocket-group") || "__ALL__", status: "all", sort: "default", view: localStorage.getItem("nezha-pocket-view") || "compact",
  serviceLoading: false, serviceError: "", services: {} as Record<string,ServiceData>, cycles: {} as Record<string,CycleTransferData>,
  detailPeriod: "realtime" as "realtime"|MetricPeriod, detailId: 0, metrics: {} as Record<string,ServerMetricsData>, monitors: [] as NezhaMonitor[], tsdb: true,
  mapCountry: sessionStorage.getItem("nezha-pocket-map-country") || "", mapRoutes: localStorage.getItem("nezha-pocket-map-routes")!=="off",
  theme: defaultThemeSettings(),
  realtime: new Map<number, Array<{ts:number;cpu:number;memory:number;disk:number;net_in_speed:number;net_out_speed:number}>>(),
};
let socket: WebSocket | null=null, reconnectTimer=0, serviceTimer=0, routeToken=0, renderDeferred=false;

function icon(name:string) { const icons:Record<string,string>={grid:"▦",list:"▤",sun:"☀",moon:"☾",globe:"文",map:"◉",gear:"⚙",refresh:"↻",back:"←",server:"▣",signal:"⌁",up:"↑",down:"↓"}; return `<span class="icon" aria-hidden="true">${icons[name]||"·"}</span>`; }
function button(label:string, action:string, options="") { return `<button class="pixel-button ${options}" data-action="${action}">${label}</button>`; }
function statusBadge() { const label=state.connected?t("online"):state.attempts?`${t("reconnect")} ${state.attempts}/30`:t("offline"); return `<span class="link-status ${state.connected?"ok":"danger"}"><i></i>${label}</span>`; }
function shell(content:string) {
  const path=location.pathname;
  const logo=state.theme.logo?`<img class="brand-logo" src="${esc(state.theme.logo)}" alt="">`:`<span class="brand-sprite"><i></i><i></i></span>`;
  const nav=`<a href="/" data-link class="${path==="/"?"active":""}">${icon("server")}${t("servers")}</a>${state.theme.showMap?`<a href="/map" data-link class="${path==="/map"?"active":""}">${icon("map")}${t("worldMap")}</a>`:""}${state.theme.showServices?`<a href="/services" data-link class="${path==="/services"?"active":""}">${icon("signal")}${t("services")}</a>`:""}`;
  const links=state.theme.links.map(x=>`<a class="footer-project" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a>`).join(" · ");
  const footer=state.theme.footerText?esc(state.theme.footerText):`${t("powered")}${state.version?` · v${esc(state.version)}`:""} · <a class="footer-project" href="https://github.com/karllao/nezha-pixel" target="_blank" rel="noopener noreferrer">GitHub / Nezha-Pixel</a>`;
  return `<div class="app-shell"><header class="topbar"><div class="topbar-inner"><a href="/" data-link class="brand" aria-label="Home">${logo}<span><b>${esc(state.siteName)}</b><small>${esc(state.theme.description)}</small></span></a><nav aria-label="Main navigation">${nav}</nav><div class="top-actions">${statusBadge()}<button class="icon-button" data-action="locale" title="${t("language")}" aria-label="${t("language")}">${locale==="zh-CN"?"EN":"中"}</button><button class="icon-button" data-action="theme" title="${t("theme")}" aria-label="${t("theme")}">${icon(document.documentElement.dataset.theme==="dark"?"sun":"moon")}</button>${state.theme.showAdmin?`<a class="pixel-button admin-button" href="/dashboard">${icon("gear")}<span>${t("admin")}</span></a>`:""}</div></div></header><main class="main-wrap">${content}</main><footer><span>${footer}${links?` · ${links}`:""}</span><span class="footer-pixels" aria-hidden="true">● ◆ ●</span></footer></div>`;
}

function stats() {
  let online=0,up=0,down=0,out=0,inc=0;
  state.servers.forEach(s=>{const i=serverInfo(state.now,s);if(i.online){online++;up+=i.up;down+=i.down;out+=i.net_out_transfer;inc+=i.net_in_transfer;}});
  return `<section class="overview" aria-label="${t("overview")}"><div class="overview-title"><span class="eyebrow">✦ ${t("overview")}</span><strong>${online}<small> / ${state.servers.length}</small></strong><span>${online} ${t("online")} · ${state.servers.length-online} ${t("offline")}</span></div><div class="stat upload-stat"><span>${icon("up")}${t("netUp")}</span><strong>${formatSpeed(up)}</strong><small>${t("traffic")} ${formatBytes(out)}</small></div><div class="stat download-stat"><span>${icon("down")}${t("netDown")}</span><strong>${formatSpeed(down)}</strong><small>${t("traffic")} ${formatBytes(inc)}</small></div><div class="stat clock"><span>${t("time")}</span><strong>${state.now?new Date(state.now).toLocaleTimeString():"--:--:--"}</strong><small><i></i>${t("live")}</small></div></section>`;
}
function bar(value:number,label:string,segments=12) { const filled=Math.round(Math.max(0,Math.min(100,value))/100*segments); return `<div class="meter ${level(value)}"><span>${label}</span><div class="meter-track" aria-label="${label} ${value.toFixed(1)}%">${Array.from({length:segments},(_,i)=>`<i class="${i<filled?"on":""}"></i>`).join("")}</div><b>${value.toFixed(1)}%</b></div>`; }
function noteTags(s:NezhaServer) {
  const note=parsePublicNote(serverInfo(state.now,s).public_note), p=note?.planDataMod, b=note?.billingDataMod, tags:string[]=[];
  if(p){ if(p.bandwidth)tags.push(p.bandwidth);if(p.trafficVol)tags.push(p.trafficVol);if(p.IPv4==="1")tags.push("IPv4");if(p.IPv6==="1")tags.push("IPv6");tags.push(...(p.networkRoute||"").split(",").filter(Boolean));tags.push(...(p.extra||"").split(",").filter(Boolean)); }
  if(b?.amount) tags.push(b.amount==="0"?t("free"):b.amount==="-1"?t("usage"):`${b.amount}/${b.cycle||""}`);
  const bill=billingInfo(b); if(bill) tags.push(bill.never?`∞ ${t("forever")}`:bill.expired?`${t("expired")} ${Math.abs(bill.days)}${t("days")}`:`${bill.days}${t("days")}`);
  return tags.length?`<div class="tag-row">${tags.map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:"";
}
function serverCard(s:NezhaServer) {
  const i=serverInfo(state.now,s), compact=state.view==="compact";
  return `<a href="/server/${s.id}" data-link class="server-card pixel-panel ${i.online?"":"offline"} ${compact?"compact":""}"><header><span class="status-pip ${i.online?"ok":"danger"}"></span><strong title="${esc(s.name)}">${esc(s.name)}</strong>${s.country_code?`<span class="country">${esc(s.country_code.toUpperCase())}</span>`:""}<span class="card-state ${i.online?"ok":"danger"}">${i.online?t("online"):t("offline")}</span></header>${i.online?`<div class="meters">${bar(i.cpu,"CPU",compact?10:16)}${bar(i.mem,"MEM",compact?10:16)}${bar(i.disk,"DISK",compact?10:16)}</div><div class="card-facts"><span>${icon("up")}<b>${formatSpeed(i.up)}</b></span><span>${icon("down")}<b>${formatSpeed(i.down)}</b></span><span>${t("load")} <b>${Number(i.load_1).toFixed(2)}</b></span><span>${t("uptime")} <b>${formatUptime(i.uptime)}</b></span></div>${state.theme.showNetTransfer&&!compact?`<div class="card-transfer"><span>${icon("up")}${formatBytes(i.net_out_transfer)}</span><span>${icon("down")}${formatBytes(i.net_in_transfer)}</span></div>`:""}${compact?"":noteTags(s)}`:`<div class="offline-message"><span>×</span><div><b>${t("offline")}</b><small>${t("lastSeen")}: ${esc(i.last_active_text||"-")}</small></div></div>`}</a>`;
}
function homePage() {
  if(!state.now&&!state.connected) return shell(`<section class="terminal-message pixel-panel"><span>&gt;</span> ${t("connecting")}</section>`);
  const tabs=[{name:"__ALL__",label:t("all")},...state.groups.filter(g=>g.servers?.some(id=>state.servers.some(s=>s.id===id))).map(g=>({name:g.group.name,label:g.group.name}))];
  let list=[...state.servers]; if(state.group!=="__ALL__"){const ids=new Set(state.groups.find(g=>g.group.name===state.group)?.servers||[]);list=list.filter(s=>ids.has(s.id));} if(state.status!=="all")list=list.filter(s=>serverInfo(state.now,s).online===(state.status==="online"));
  list.sort((a,b)=>{const x=serverInfo(state.now,a),y=serverInfo(state.now,b);if(state.sort!=="name"&&x.online!==y.online)return x.online?-1:1;const map:Record<string,number>={cpu:y.cpu-x.cpu,memory:y.mem-x.mem,disk:y.disk-x.disk,up:y.up-x.up,down:y.down-x.down};return state.sort==="name"?a.name.localeCompare(b.name):map[state.sort]||0;});
  const controls=`<section class="control-deck"><div class="group-tabs" role="tablist">${tabs.map(x=>`<button role="tab" aria-selected="${state.group===x.name}" class="${state.group===x.name?"active":""}" data-group="${esc(x.name)}">${esc(x.label)}</button>`).join("")}</div><div class="filters"><label>${t("status")}<select data-control="status"><option value="all" ${state.status==="all"?"selected":""}>${t("all")}</option><option value="online" ${state.status==="online"?"selected":""}>${t("online")}</option><option value="offline" ${state.status==="offline"?"selected":""}>${t("offline")}</option></select></label><label>${t("sort")}<select data-control="sort">${[["default",t("default")],["name",t("name")],["cpu","CPU"],["memory",t("memory")],["disk",t("disk")],["up",t("up")],["down",t("down")]].map(([v,l])=>`<option value="${v}" ${state.sort===v?"selected":""}>${l}</option>`).join("")}</select></label><div class="segmented" aria-label="View mode"><button data-view="compact" class="${state.view==="compact"?"active":""}" title="${t("compact")}">${icon("list")}</button><button data-view="detail" class="${state.view==="detail"?"active":""}" title="${t("detail")}">${icon("grid")}</button></div></div></section>`;
  return shell(`${stats()}${controls}<section class="server-grid ${state.view}">${list.map(serverCard).join("")}</section>${list.length?"":`<div class="empty-state pixel-panel"><span>□</span><p>${t("noServers")}</p></div>`}`);
}

function kv(k:string,v:string){return `<div class="kv"><span>${k}</span><strong>${v}</strong></div>`;}
function detailPage(id:number) {
  const s=state.servers.find(x=>x.id===id); if(!s)return shell(`${button(`${icon("back")}${t("back")}`,"back","back-button")}<div class="terminal-message pixel-panel">${state.now?`${t("serverMissing")} #${id}`:t("connecting")}</div>`);
  const i=serverInfo(state.now,s), note=parsePublicNote(i.public_note), p=note?.planDataMod, b=note?.billingDataMod, tags=[p?.bandwidth,p?.trafficVol,p?.IPv4==="1"?"IPv4":"",p?.IPv6==="1"?"IPv6":"",...(p?.networkRoute||"").split(","),...(p?.extra||"").split(",")].filter(Boolean); const bill=billingInfo(b);
  if(b?.amount)tags.push(b.amount==="0"?t("free"):b.amount==="-1"?t("usage"):`${b.amount}/${b.cycle||""}`);if(bill)tags.push(bill.never?`∞ ${t("forever")}`:bill.expired?`${t("expired")} ${Math.abs(bill.days)}${t("days")}`:`${bill.days}${t("days")}`);
  const system=kv(t("platform"),`${esc(i.platform||"-")} <small>${esc(i.platform_version)}</small>`)+kv(t("arch"),esc(i.arch||"-"))+kv(t("agent"),`v${esc(i.version||"-")}`)+kv(t("region"),esc(s.country_code?.toUpperCase()||"-"))+kv(t("boot"),formatTime(i.boot_time*1000))+kv(t("uptime"),formatUptime(i.uptime))+kv(t("lastSeen"),esc(i.last_active_text||"-"));
  const host=kv("CPU",i.cpu_info.length?i.cpu_info.map(esc).join("<br>"):"-")+(i.gpu_info.length?kv("GPU",i.gpu_info.map(esc).join("<br>")):"")+kv(t("memory"),`${formatBytes(i.mem_used)} / ${formatBytes(i.mem_total)}`)+kv(t("swap"),`${formatBytes(i.swap_used)} / ${formatBytes(i.swap_total)} (${i.swap.toFixed(1)}%)`)+kv(t("disk"),`${formatBytes(i.disk_used)} / ${formatBytes(i.disk_total)}`)+(i.temperatures.length?kv(t("temperature"),i.temperatures.map(x=>`${esc(x.Name)} ${x.Temperature.toFixed(1)}°C`).join("<br>")):"");
  const network=kv(`${t("up")} / ${t("down")}`,`${formatSpeed(i.up)} / ${formatSpeed(i.down)}`)+kv(t("transfer"),`↑ ${formatBytes(i.net_out_transfer)}<br>↓ ${formatBytes(i.net_in_transfer)}`)+kv(t("connections"),`${i.tcp} / ${i.udp}`)+kv(t("processes"),String(i.process))+kv(t("load"),`${Number(i.load_1).toFixed(2)} / ${Number(i.load_5).toFixed(2)} / ${Number(i.load_15).toFixed(2)}`);
  const periods:[[string,string]]|any=[["realtime",t("realtime")],["1d",t("day")],["7d",t("week")],["30d",t("month")]];
  const graphs=(["cpu","memory","disk","net_in_speed","net_out_speed"] as MetricType[]).map((m,idx)=>chart(pointsFor(id,m),m==="memory"?"MEM":m==="net_in_speed"?"NET ↓":m==="net_out_speed"?"NET ↑":m.toUpperCase(),m.includes("speed")?"bytes":"percent",["cyan","yellow","green","orange","red"][idx],m.includes("speed")?undefined:100)).join("");
  const monitorCharts=state.monitors.map(m=>chart((m.created_at||[]).map((ts,n)=>({ts,value:m.avg_delay[n]||0})),m.monitor_name,"ms","cyan")).join("");
  return shell(`<div class="detail-page">${button(`${icon("back")}${t("back")}`,"back","back-button")}<section class="server-hero pixel-panel"><header><span class="status-pip ${i.online?"ok":"danger"}"></span><div><small>NODE #${s.id}</small><h1>${esc(s.name)}</h1></div>${s.country_code?`<span class="country">${esc(s.country_code.toUpperCase())}</span>`:""}<span class="hero-state ${i.online?"ok":"danger"}">${i.online?t("online"):t("offline")}</span></header>${tags.length?`<div class="tag-row">${tags.map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}<div class="hero-meters">${bar(i.cpu,"CPU",20)}${bar(i.mem,"MEM",20)}${bar(i.disk,"DISK",20)}</div><div class="info-grid"><article><h2>${t("system")}</h2>${system}</article><article><h2>${t("host")}</h2>${host}</article><article><h2>${t("network")}</h2>${network}</article></div></section><section class="chart-section"><header class="section-head"><div><span class="eyebrow">TELEMETRY</span><h2>${t("history")}</h2></div>${state.detailPeriod==="realtime"?`<span class="live-count"><i></i>${t("realtime")} · ${(state.realtime.get(id)||[]).length} PTS</span>`:""}<div class="period-tabs">${periods.map(([v,l]:string[])=>`<button data-period="${v}" ${v!=="realtime"&&!state.tsdb?"disabled":""} class="${state.detailPeriod===v?"active":""}">${l}</button>`).join("")}</div></header>${!state.tsdb&&state.detailPeriod!=="realtime"?`<div class="terminal-message pixel-panel danger">${t("tsdbOff")}</div>`:`<div class="chart-grid">${graphs}</div>`}</section>${monitorCharts?`<section class="chart-section"><header class="section-head"><div><span class="eyebrow">24H</span><h2>${t("monitors")}</h2></div></header><div class="chart-grid">${monitorCharts}</div></section>`:""}</div>`);
}
function pointsFor(id:number,m:MetricType):MetricDataPoint[]{ if(state.detailPeriod==="realtime")return (state.realtime.get(id)||[]).map(p=>({ts:p.ts,value:p[m]})); return state.metrics[m]?.data_points||[]; }

function uptime(s:ServiceData){const up=(s.up||[]).reduce((a,b)=>a+b,0),down=(s.down||[]).reduce((a,b)=>a+b,0);return up+down?up/(up+down)*100:0;}

function countryLabel(code:string){try{return new Intl.DisplayNames([locale],{type:"region"}).of(code)||code;}catch{return code;}}
function mapPage(){
  if(!state.now&&!state.connected)return shell(`<section class="terminal-message pixel-panel"><span>&gt;</span> ${t("connecting")}</section>`);
  const located=new Map<string,{code:string;servers:NezhaServer[];x:number;y:number}>(),unknown:NezhaServer[]=[];
  for(const server of state.servers){const code=(server.country_code||"").trim().toUpperCase(),point=countryPoint(code);if(!point){unknown.push(server);continue;}const group=located.get(code)||{code,servers:[],...point};group.servers.push(server);located.set(code,group);}
  const places=[...located.values()].sort((a,b)=>b.servers.length-a.servers.length||a.code.localeCompare(b.code));
  if(state.mapCountry&&!located.has(state.mapCountry))state.mapCountry="";
  const selected=located.get(state.mapCountry)||places[0],origin=selected;
  const onlineTotal=state.servers.filter(s=>serverInfo(state.now,s).online).length;
  const selectedOnline=selected?.servers.filter(s=>serverInfo(state.now,s).online).length||0;
  const routes=state.mapRoutes&&origin?places.filter(p=>p.code!==origin.code).slice(0,18).map(p=>{const x1=origin.x*10,y1=origin.y*5,x2=p.x*10,y2=p.y*5,mid=(x1+x2)/2,lift=Math.min(85,Math.abs(x2-x1)*.12+25);return `<path d="M${x1} ${y1} Q${mid} ${Math.min(y1,y2)-lift} ${x2} ${y2}"/>`;}).join(""):"";
  const nodes=places.map(p=>{const online=p.servers.filter(s=>serverInfo(state.now,s).online).length,active=p.code===selected?.code;return `<button class="map-node ${online?"online":"offline"} ${active?"active":""}" style="--x:${p.x}%;--y:${p.y}%" data-map-country="${p.code}" aria-label="${esc(countryLabel(p.code))}: ${online}/${p.servers.length} ${t("online")}" aria-pressed="${active}"><i></i>${p.servers.length>1?`<b>${p.servers.length}</b>`:""}<span class="map-node-tip"><strong>${esc(countryLabel(p.code))}</strong><small>${online}/${p.servers.length} ${t("online")} · ${t("clickExplore")}</small></span></button>`;}).join("");
  const serverRows=selected?.servers.map(s=>{const i=serverInfo(state.now,s);return `<a href="/server/${s.id}" data-link class="map-server-row"><span class="status-pip ${i.online?"ok":"danger"}"></span><span><strong>${esc(s.name)}</strong><small>${i.online?`${formatSpeed(i.up)} ↑ · ${formatSpeed(i.down)} ↓`:t("offline")}</small></span><b>${i.online?`${i.cpu.toFixed(0)}% CPU`:"--"}</b><span aria-hidden="true">→</span></a>`;}).join("")||"";
  const placeButtons=places.map(p=>{const online=p.servers.filter(s=>serverInfo(state.now,s).online).length;return `<button data-map-country="${p.code}" class="map-place ${p.code===selected?.code?"active":""}"><span>${esc(countryLabel(p.code))}<small>${p.code}</small></span><b>${online}<small> / ${p.servers.length}</small></b></button>`;}).join("");
  return shell(`<div class="map-page"><header class="page-title map-title"><div><span class="eyebrow">GLOBAL NODE EXPLORER</span><h1>${t("mapTitle")}</h1><p>${t("mapIntro")}</p></div><button class="pixel-button ${state.mapRoutes?"active":""}" data-action="map-routes">${icon("signal")}${t("signalRoutes")}</button></header><section class="map-summary"><div><span>${t("mappedRegions")}</span><strong>${places.length}</strong><small>${unknown.length?`${unknown.length} ${t("unmapped")}`:t("allMapped")}</small></div><div><span>${t("globalNodes")}</span><strong>${state.servers.length}</strong><small>${onlineTotal} ${t("online")}</small></div><div><span>${t("selectedRegion")}</span><strong>${selected?esc(selected.code):"--"}</strong><small>${selected?`${selectedOnline}/${selected.servers.length} ${t("online")}`:t("noLocationData")}</small></div></section><div class="map-layout"><section class="world-card pixel-panel"><div class="map-toolbar"><span><i class="map-live-dot"></i>${t("liveCoordinates")}</span><small>${t("mapHint")}</small></div><div class="world-stage" data-world-stage><svg class="world-svg" viewBox="0 0 1000 500" role="img" aria-label="${t("worldMap")}"><g class="map-grid-lines"><path d="M0 125H1000M0 250H1000M0 375H1000M250 0V500M500 0V500M750 0V500"/></g><g class="map-land">${worldLand}</g><g class="map-borders">${worldBorders}</g><g class="map-routes">${routes}</g></svg><div class="radar-sweep" aria-hidden="true"></div>${nodes||`<div class="map-empty">${t("noLocationData")}</div>`}<span class="map-coordinates" aria-hidden="true">LAT 00.00 · LNG 00.00</span></div></section><aside class="map-side pixel-panel"><header><div><span class="eyebrow">${t("selectedRegion")}</span><h2>${selected?esc(countryLabel(selected.code)):t("noLocationData")}</h2></div>${selected?`<span class="country">${selected.code}</span>`:""}</header><div class="map-server-list">${serverRows||`<p class="map-side-empty">${t("pickRegion")}</p>`}</div><div class="map-place-list"><span>${t("regions")}</span>${placeButtons||`<small>${t("noLocationData")}</small>`}</div></aside></div></div>`);
}

function servicesPage(){const list=Object.values(state.services);const services=list.map(s=>{const pct=uptime(s),offset=Math.max(0,s.up.length-50);return `<article class="service-card pixel-panel"><header><span class="status-pip ${pct>=95?"ok":"danger"}"></span><strong>${esc(s.service_name)}</strong><b class="${pct>=99?"ok":pct>=95?"warn":"danger"}">${pct.toFixed(2)}%</b></header><div class="service-facts"><span>${t("currentUp")}<b>${s.current_up}</b></span><span>${t("currentDown")}<b>${s.current_down}</b></span><span>${t("avgDelay")}<b>${((s.delay||[]).reduce((a,b)=>a+b,0)/(s.delay?.length||1)).toFixed(1)} ms</b></span></div><div class="timeline">${s.up.slice(-50).map((v,i)=>`<i class="${v>(s.down[offset+i]||0)?"ok":"danger"}"></i>`).join("")}</div></article>`;}).join("");
  const cycles=Object.entries(state.cycles).map(([key,c])=>`<article class="cycle-card pixel-panel"><header><strong>${esc(c.name||key)}</strong></header>${Object.entries(c.transfer||{}).map(([sid,val])=>{const max=typeof c.max==="number"?c.max:c.max?.[sid]||0,from=typeof c.from==="string"?c.from:c.from?.[sid]||"",to=typeof c.to==="string"?c.to:c.to?.[sid]||"";return `<div class="cycle-row"><div><b>${esc(c.server_name?.[sid]||sid)}</b><small>${esc(from)} → ${esc(to)}</small></div><div class="traffic-bar"><i style="width:${Math.min(100,val/(max||1)*100)}%"></i></div><div><span>${formatBytes(val)} / ${formatBytes(max)}</span>${c.next_update?.[sid]?`<small>${t("next")}: ${esc(c.next_update[sid])}</small>`:""}</div></div>`;}).join("")}</article>`).join("");
  const body=state.serviceLoading&&!list.length?`<div class="terminal-message pixel-panel">${t("loading")}</div>`:state.serviceError?`<div class="terminal-message pixel-panel danger">${t("error")}: ${esc(state.serviceError)}</div>`:`${services?`<section><h2 class="block-title">${t("uptimeMonitors")}</h2><div class="service-grid">${services}</div></section>`:""}${cycles?`<section><h2 class="block-title">${t("cycleTraffic")}</h2><div class="service-grid">${cycles}</div></section>`:""}${!services&&!cycles?`<div class="empty-state pixel-panel"><span>□</span><p>${t("noServices")}</p></div>`:""}`;
  return shell(`<div class="services-page"><header class="page-title"><div><span class="eyebrow">UPTIME & BANDWIDTH</span><h1>${t("serviceTitle")}</h1></div>${button(`${icon("refresh")}${t("refresh")}`,"refresh-services")}</header>${body}</div>`);
}
function notFound(){return shell(`<div class="not-found"><strong>404</strong><h1>${t("notFound")}</h1><a href="/" data-link class="pixel-button">${icon("back")}${t("home")}</a></div>`);}
function currentRoute(){const match=location.pathname.match(/^\/server\/(\d+)\/?$/);return match?{kind:"detail",id:Number(match[1])}:location.pathname==="/"?{kind:"home"}:location.pathname==="/map"?{kind:"map"}:location.pathname==="/services"?{kind:"services"}:{kind:"404"};}
function render(force=false){
  const active=document.activeElement;
  if(!force&&active instanceof HTMLSelectElement&&active.dataset.control){renderDeferred=true;return;}
  renderDeferred=false;
  const radarTime=Number(document.querySelector<HTMLElement>(".radar-sweep")?.getAnimations()[0]?.currentTime||0);
  const route=currentRoute(); root.innerHTML=route.kind==="home"?homePage():route.kind==="map"?mapPage():route.kind==="services"?servicesPage():route.kind==="detail"?detailPage(route.id!):notFound(); bindCharts();bindMap();
  if(radarTime){const radarAnimation=document.querySelector<HTMLElement>(".radar-sweep")?.getAnimations()[0];if(radarAnimation)radarAnimation.currentTime=radarTime;}
}
async function routeChanged(){clearInterval(serviceTimer);const token=++routeToken,route=currentRoute();if(route.kind==="services"){await loadServices();if(token===routeToken)serviceTimer=window.setInterval(loadServices,30000);}if(route.kind==="detail"&&route.id!==state.detailId){state.detailId=route.id!;state.detailPeriod="realtime";state.metrics={};state.monitors=[];try{const res=await fetchMonitor(route.id!,"1d");if(token===routeToken)state.monitors=res.data||[];}catch{} }render();}
async function loadServices(){state.serviceLoading=true;state.serviceError="";render();try{const r=await fetchService();state.services=r.data?.services||{};state.cycles=r.data?.cycle_transfer_stats||{};}catch(e){state.serviceError=(e as Error).message;}finally{state.serviceLoading=false;render();}}
async function loadHistory(period:MetricPeriod){state.detailPeriod=period;state.metrics={};render();const metrics:MetricType[]=["cpu","memory","disk","net_in_speed","net_out_speed"];let ok=false;await Promise.all(metrics.map(async m=>{try{const r=await fetchServerMetrics(state.detailId,m,period);state.metrics[m]=r.data;ok=true;}catch{}}));state.tsdb=ok;render();}

function navigate(url:string){history.pushState({},"",url);routeChanged();}
root.addEventListener("click",e=>{const el=(e.target as HTMLElement).closest<HTMLElement>("[data-link],[data-action],[data-group],[data-view],[data-period],[data-map-country]");if(!el)return;if(el.hasAttribute("data-link")){e.preventDefault();navigate((el as HTMLAnchorElement).getAttribute("href")!);return;}const action=el.dataset.action;if(action==="theme"){const theme=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=theme;localStorage.setItem("nezha-pocket-theme",theme);render();}if(action==="locale"){toggleLocale();render();}if(action==="back")history.length>1?history.back():navigate("/");if(action==="refresh-services")loadServices();if(action==="map-routes"){state.mapRoutes=!state.mapRoutes;localStorage.setItem("nezha-pocket-map-routes",state.mapRoutes?"on":"off");render();}if(el.dataset.mapCountry){state.mapCountry=el.dataset.mapCountry;sessionStorage.setItem("nezha-pocket-map-country",state.mapCountry);render();}if(el.dataset.group){state.group=el.dataset.group;sessionStorage.setItem("nezha-pocket-group",state.group);render();}if(el.dataset.view){state.view=el.dataset.view;localStorage.setItem("nezha-pocket-view",state.view);render();}if(el.dataset.period){const p=el.dataset.period as "realtime"|MetricPeriod;p==="realtime"?(state.detailPeriod=p,render()):loadHistory(p);}});
root.addEventListener("change",e=>{const el=e.target as HTMLSelectElement;if(el.dataset.control==="status")state.status=el.value;if(el.dataset.control==="sort")state.sort=el.value;render(true);});
root.addEventListener("focusout",e=>{const el=e.target as HTMLElement;if(el instanceof HTMLSelectElement&&el.dataset.control&&renderDeferred)window.setTimeout(()=>render(),0);});
window.addEventListener("popstate",routeChanged);

function bindCharts(){document.querySelectorAll<HTMLElement>("[data-chart]").forEach(el=>{const stage=el.querySelector<HTMLElement>(".chart-stage")!,cursor=el.querySelector<HTMLElement>(".chart-cursor")!,tip=el.querySelector<HTMLOutputElement>(".chart-tip")!,points=JSON.parse(el.dataset.chart||"[]") as MetricDataPoint[];stage.onpointermove=e=>{if(!points.length)return;const r=stage.getBoundingClientRect(),pct=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),idx=Math.round(pct*(points.length-1)),p=points[idx];cursor.hidden=false;tip.hidden=false;cursor.style.left=`${pct*100}%`;tip.style.left=`${pct*100}%`;tip.classList.toggle("flip",pct>.58);tip.innerHTML=`<b>${formatValue(p.value,el.dataset.format||"raw")}</b><small>${new Date(p.ts).toLocaleString()}</small>`;};stage.onpointerleave=()=>{cursor.hidden=true;tip.hidden=true;};});}
function bindMap(){const stage=document.querySelector<HTMLElement>("[data-world-stage]");if(!stage)return;stage.onpointermove=e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;stage.style.setProperty("--tilt-x",`${(x-.5)*8}px`);stage.style.setProperty("--tilt-y",`${(y-.5)*8}px`);const label=stage.querySelector<HTMLElement>(".map-coordinates");if(label)label.textContent=`LAT ${((.5-y)*180).toFixed(2)} · LNG ${((x-.5)*360).toFixed(2)}`;};stage.onpointerleave=()=>{stage.style.setProperty("--tilt-x","0px");stage.style.setProperty("--tilt-y","0px");};}

function connect(){if(socket?.readyState===WebSocket.OPEN)return;const u=new URL("/api/v1/ws/server",location.origin);u.protocol=u.protocol.replace("http","ws");socket=new WebSocket(u);socket.onopen=()=>{state.connected=true;state.attempts=0;render();};socket.onmessage=e=>{try{const data=JSON.parse(e.data);state.now=data.now;state.servers=data.servers||[];for(const s of state.servers){const i=serverInfo(state.now,s),arr=state.realtime.get(s.id)||[];if(!arr.length||arr.at(-1)!.ts!==state.now){arr.push({ts:state.now,cpu:i.cpu,memory:i.mem,disk:i.disk,net_in_speed:i.down,net_out_speed:i.up});if(arr.length>120)arr.splice(0,arr.length-120);state.realtime.set(s.id,arr);}}render();}catch{}};socket.onclose=()=>{state.connected=false;socket=null;if(state.attempts<30){state.attempts++;reconnectTimer=window.setTimeout(connect,3000);}render();};socket.onerror=()=>socket?.close();}
async function init(){render();connect();try{const [setting,groups]=await Promise.all([fetchSetting(),fetchServerGroup()]);state.siteName=setting.data?.config?.site_name||state.siteName;state.version=setting.data?.version||"";state.tsdb=setting.data?.tsdb_enabled!==false;useBackendLocale(setting.data?.config?.language||"");installCustomCode(setting.data?.config?.custom_code||"");state.theme=readThemeSettings();applyThemeSettings(state.theme);if(state.theme.forceCardInline){state.view="compact";}state.groups=groups.data||[];document.title=state.theme.description?`${state.siteName} · ${state.theme.description}`:state.siteName;}catch{}routeChanged();}
window.addEventListener("beforeunload",()=>{clearTimeout(reconnectTimer);clearInterval(serviceTimer);socket?.close();});
init();
