import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";

const now=Date.now();
const server=(id,name,country,cpu,online=true)=>({id,name,country_code:country,public_note:JSON.stringify({billingDataMod:{startDate:"2026-01-01",endDate:"2027-01-01",autoRenewal:"0",cycle:"年",amount:"$24"},planDataMod:{bandwidth:"1 Gbps",trafficVol:"2 TB",IPv4:"1",IPv6:"1",networkRoute:"CN2"}}),last_active:online?new Date(now-4000).toISOString():new Date(now-600000).toISOString(),host:{platform:"debian",platform_version:"12",cpu:["AMD EPYC 7B13 4-Core"],gpu:[],mem_total:8589934592,disk_total:107374182400,swap_total:2147483648,arch:"x86_64",boot_time:Math.floor((now-864000000)/1000),version:"1.12.0"},state:{cpu,mem_used:3221225472,swap_used:0,disk_used:38654705664,net_in_transfer:128849018880,net_out_transfer:64424509440,net_in_speed:4587520,net_out_speed:1572864,uptime:864000,load_1:.42,load_5:.37,load_15:.31,tcp_conn_count:83,udp_conn_count:12,process_count:146,temperatures:[{Name:"CPU",Temperature:51.5}],gpu:[]}});
const servers=[server(1,"Shanghai Edge / Alpha","cn",34),server(2,"Tokyo Compute-02","jp",72),server(3,"Frankfurt Archive","de",8,false),server(4,"Singapore Relay","sg",46)];
const metrics=Array.from({length:48},(_,i)=>({ts:now-(47-i)*1800000,value:30+Math.sin(i/4)*18+i/3}));
await mkdir("screenshots",{recursive:true});
const browser=await chromium.launch({headless:true});

async function context(width,height){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});await ctx.addInitScript(({payload,now})=>{const NativeSocket=window.WebSocket;class FakeSocket{static OPEN=1;readyState=1;onopen=null;onmessage=null;onclose=null;onerror=null;constructor(){window.__pushServers=()=>this.onmessage?.({data:JSON.stringify({now:Date.now(),servers:payload})});setTimeout(()=>{this.onopen?.({});this.onmessage?.({data:JSON.stringify({now,servers:payload})});},30);setTimeout(()=>this.onmessage?.({data:JSON.stringify({now:now+1000,servers:payload})}),220)}close(){}};window.WebSocket=function(url,protocols){return String(url).includes("/api/v1/ws/server")?new FakeSocket():new NativeSocket(url,protocols)};window.WebSocket.OPEN=1;}, {payload:servers,now});await ctx.route("**/api/v1/**",async route=>{const u=new URL(route.request().url());let data={success:true,data:{}};if(u.pathname.endsWith("/setting"))data={success:true,data:{config:{site_name:"Nezha Pocket Lab",language:"zh-CN",custom_code:'<style>.overview{--custom-check:1}</style><script>window.CustomDesc="CUSTOM CONSOLE";window.CustomLinks=JSON.stringify([{name:"Docs",link:"https://nezha.wiki"}]);window.ForceTheme="dark";window.ShowNetTransfer=true;window.NezhaPocketConfig={accentColor:"#8b7cf6"};</script>'},version:"1.12.0",tsdb_enabled:true}};else if(u.pathname.endsWith("/server-group"))data={success:true,data:[{group:{id:1,name:"亚洲节点"},servers:[1,2,4]},{group:{id:2,name:"归档"},servers:[3]}]};else if(u.pathname.endsWith("/service")){if(/server\/\d+\/service/.test(u.pathname))data={success:true,data:[{monitor_id:1,monitor_name:"ICMP Ping",server_id:1,server_name:"Shanghai",created_at:metrics.map(x=>x.ts),avg_delay:metrics.map((_,i)=>26+Math.sin(i/3)*4)}]};else data={success:true,data:{services:{ping:{service_name:"Global HTTPS",current_up:4,current_down:0,total_up:1398,total_down:2,delay:[35,39,31],up:Array(40).fill(1),down:Array(40).fill(0)}},cycle_transfer_stats:{monthly:{name:"Monthly Transfer",from:"2026-07-01",to:"2026-08-01",max:1099511627776,min:0,server_name:{"1":"Shanghai Edge"},transfer:{"1":438086664192},next_update:{"1":"2026-08-01"}}}}};}else if(u.pathname.endsWith("/metrics"))data={success:true,data:{server_id:1,server_name:"Shanghai",metric:u.searchParams.get("metric"),data_points:metrics}};await route.fulfill({json:data});});return ctx;}

const errors=[];
let ctx=await context(1440,1050),page=await ctx.newPage();page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));await page.goto("http://localhost:4321/");await page.waitForSelector(".server-card");if(!await page.locator('[data-action="theme"]').count())errors.push("ForceTheme incorrectly hid the theme switch");if((await page.locator(".brand small").textContent())!=="CUSTOM CONSOLE")errors.push("CustomDesc was not applied");if(await page.locator(".card-transfer").count())errors.push("Compact mode displayed ShowNetTransfer data");await page.locator('[data-view="detail"]').click();if(!await page.locator(".card-transfer").count())errors.push("ShowNetTransfer was not applied in detail mode");if(!await page.locator('footer a[href="https://nezha.wiki"]').count())errors.push("CustomLinks was not applied");await page.locator('select[data-control="status"]').focus();await page.waitForTimeout(300);const selectStillFocused=await page.evaluate(()=>document.activeElement?.getAttribute("data-control")==="status");if(!selectStillFocused)errors.push("Realtime render replaced the focused filter select");await page.locator('select[data-control="status"]').blur();await page.waitForTimeout(150);await page.screenshot({path:"screenshots/home-desktop.png",fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(overflow)errors.push("Desktop home has horizontal overflow");await page.click('a[href="/map"]');await page.waitForSelector(".map-node");await page.click('[data-map-country="JP"]');await page.waitForTimeout(250);if(!(await page.locator(".map-side h2").textContent())?.includes("日本"))errors.push("Map country selection did not update the detail panel");const radarBefore=await page.evaluate(()=>Number(document.querySelector(".radar-sweep")?.getAnimations()[0]?.currentTime||0));await page.evaluate(()=>window.__pushServers());await page.waitForTimeout(80);const radarAfter=await page.evaluate(()=>Number(document.querySelector(".radar-sweep")?.getAnimations()[0]?.currentTime||0));if(radarAfter<radarBefore)errors.push(`Radar animation restarted after realtime update (${radarBefore} -> ${radarAfter})`);await page.screenshot({path:"screenshots/map-desktop.png",fullPage:true});const mapOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(mapOverflow)errors.push("Desktop map has horizontal overflow");await page.click('a[href="/server/2"]');await page.waitForSelector(".server-hero");await page.waitForTimeout(450);await page.screenshot({path:"screenshots/detail-desktop.png",fullPage:true});await ctx.close();

ctx=await context(390,844);page=await ctx.newPage();page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));await page.goto("http://localhost:4321/");await page.waitForSelector(".server-card");await page.waitForTimeout(450);await page.screenshot({path:"screenshots/home-mobile.png",fullPage:true});const mobileHomeOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(mobileHomeOverflow)errors.push("Mobile home has horizontal overflow");await page.click('a[href="/map"]');await page.waitForSelector(".map-node");await page.waitForTimeout(250);await page.screenshot({path:"screenshots/map-mobile.png",fullPage:true});const mobileMapOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(mobileMapOverflow)errors.push("Mobile map has horizontal overflow");await page.click('a[href="/services"]');await page.waitForSelector(".service-card");await page.waitForTimeout(450);await page.screenshot({path:"screenshots/services-mobile.png",fullPage:true});const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(mobileOverflow)errors.push("Mobile services has horizontal overflow");await ctx.close();await browser.close();
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log("Visual checks passed: home, map, detail and services across desktop/mobile; no console errors or horizontal overflow.");
